# Generated by Django 3.2.7 on 2021-09-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0002_category_cimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cdes',
            field=models.ImageField(upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pimg',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
