# Generated by Django 3.2.7 on 2021-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0006_alter_category_cimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pdes',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
